### ISSUE TITLE
Change the description of the repository

### ISSUE THREAD

**Issue by wiibaa** [sdmx-twg/sdmx-csv#4]
I suppose this statement is obsolete

_This repository is used for maintaining the draft proposal for SDMX-CSV message specifications. This is an early draft and there are no guarantee it will lead to a future SDMX-CSV specification._

**Comment by dosse** [comment]
Where do you see this text? Normally, the description was updated.

**Comment by wiibaa** [comment]
![image](https://user-images.githubusercontent.com/659227/47131885-6c19d500-d2a1-11e8-94fa-49e2b2431d95.png)

**Comment by dosse** [comment]
Ah, ok. I oversaw that. It will be updated as soon as possible. Thanks for spotting this!
